"""update news text fields

Revision ID: 48e502f0a828
Revises: a67ffdd70c44
Create Date: 2026-05-26 13:10:58.558303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48e502f0a828'
down_revision = 'a67ffdd70c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('info_news', 'title',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=500),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('info_news', 'digest',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('info_news', 'digest',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               existing_nullable=False)
    op.alter_column('info_news', 'title',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=500),
               nullable=True)
    # ### end Alembic commands ###
